# This file is a part of the Sylius package.
# (c) Paweł Jędrzejewski

easy_shop_account_order:
    resource: "@EasyShopBundle/Resources/config/routing/account/order.yml"
    prefix: /orders

easy_shop_account_address_book:
    resource: "@EasyShopBundle/Resources/config/routing/account/address_book.yml"
    prefix: /address-book

easy_shop_account_root:
    path: /
    methods: [GET]
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController:redirectAction
        route: easy_shop_account_dashboard
        permanent: true

easy_shop_account_dashboard:
    path: /dashboard
    methods: [GET]
    defaults:
        _controller: sylius.controller.customer:showAction
        _sylius:
            template: "@EasyShop/front/Account/dashboard.html.twig"
            repository:
                method: find
                arguments:
                    - "expr:service('sylius.context.customer').getCustomer()"

easy_shop_account_profile_update:
    path: /profile/edit
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.customer:updateAction
        _sylius:
            template: "@EasyShop/front/Account/profileUpdate.html.twig"
            form: Sylius\Bundle\CustomerBundle\Form\Type\CustomerProfileType
            repository:
                method: find
                arguments:
                    - "expr:service('sylius.context.customer').getCustomer()"
            redirect:
                route: easy_shop_account_profile_update
                parameters: {}

easy_shop_account_change_password:
    path: /change-password
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.shop_user:changePasswordAction
        _sylius:
            template: "@EasyShop/front/Account/changePassword.html.twig"
            redirect: easy_shop_account_dashboard
