# This file is a part of the Sylius package.
# (c) Paweł Jędrzejewski

easy_shop_cart_summary:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:summaryAction
        _sylius:
            template: "@EasyShop/front/Cart/summary.html.twig"
            form: Sylius\Bundle\OrderBundle\Form\Type\CartType

easy_shop_cart_save:
    path: /
    methods: [PUT, PATCH]
    defaults:
        _controller: sylius.controller.order:saveAction
        _sylius:
            template: "@EasyShop/front/Cart/summary.html.twig"
            redirect: easy_shop_cart_summary
            form: Sylius\Bundle\OrderBundle\Form\Type\CartType
            flash: sylius.cart.save

easy_shop_cart_clear:
    path: /
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.order:clearAction
        _sylius:
            redirect: easy_shop_cart_summary

easy_shop_cart_item_remove:
    path: /{id}/remove
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.order_item:removeAction
        _sylius:
            flash: sylius.cart.remove_item
            redirect:
                route: easy_shop_cart_summary
                parameters: {}
