# This file is a part of the Sylius package.
# (c) Paweł Jędrzejewski

easy_shop_login:
    path: /login
    methods: [GET]
    defaults:
        _controller: sylius.controller.security:loginAction
        _sylius:
            template: "@EasyShop/front/login.html.twig"
            logged_in_route: easy_shop_account_dashboard

easy_shop_login_check:
    path: /login-check
    methods: [POST]
    defaults:
        _controller: sylius.controller.security:checkAction

easy_shop_logout:
    path: /logout
    methods: [GET]

easy_shop_register:
    path: /register
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.customer:createAction
        _sylius:
            template: "@EasyShop/front/register.html.twig"
            form: Sylius\Bundle\CoreBundle\Form\Type\Customer\CustomerRegistrationType
            event: register
            redirect:
                route: easy_shop_account_dashboard
            flash: sylius.customer.register

easy_shop_register_after_checkout:
    path: /register-after-checkout/{tokenValue}
    methods: [GET]
    defaults:
        _controller: sylius.controller.customer:createAction
        _sylius:
            form: Sylius\Bundle\CoreBundle\Form\Type\Customer\CustomerRegistrationType
            factory:
                method: ['expr:service("sylius.factory.customer_after_checkout")', 'createAfterCheckout']
                arguments:
                    - 'expr:service("sylius.repository.order").findOneByTokenValue($tokenValue)'
            template: "@EasyShop/front/register.html.twig"
            event: register
            redirect:
                route: easy_shop_account_dashboard
            flash: sylius.customer.register

easy_shop_request_password_reset_token:
    path: /forgotten-password
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.shop_user:requestPasswordResetTokenAction
        _sylius:
            template: "@EasyShop/front/Account/requestPasswordReset.html.twig"
            redirect: easy_shop_login

easy_shop_password_reset:
    path: /forgotten-password/{token}
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.shop_user:resetPasswordAction
        _sylius:
            template: "@EasyShop/front/Account/resetPassword.html.twig"
            redirect: easy_shop_login
