# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

easy_shop_user_request_verification_token:
    path: /verify
    methods: [POST]
    defaults:
        _controller: sylius.controller.shop_user:requestVerificationTokenAction

easy_shop_user_verification:
    path: /verify/{token}
    methods: [GET]
    defaults:
        _controller: sylius.controller.shop_user:verifyAction
        _sylius:
            redirect: easy_shop_account_dashboard
