easy_shop_product_show:
  path: /{slug}
  methods: [GET]
  defaults:
    _controller: sylius.controller.product:showAction
    _sylius:
      template: "@EasyShop/front/Product/show.html.twig"
      repository:
        method: findOneByChannelAndSlug
        arguments:
          - "expr:service('sylius.context.channel').getChannel()"
          - "expr:service('sylius.context.locale').getLocaleCode()"
          - $slug
  requirements:
    slug: .+
  condition: "request.attributes.has('_easy_shop_product')"
