sylius_shop_product_index:
  path: /{slug}
  methods: [GET]
  defaults:
    _controller: sylius.controller.product:indexAction
    _sylius:
      template: "@EasyShop/front/Product/index.html.twig"
      grid: sylius_shop_product
      repository:
        method: findOneBySlug
        arguments:
          - $slug
          - "expr:service('sylius.context.locale').getLocaleCode()"
  requirements:
    slug: .+
  condition: "request.attributes.has('_sylius_shop_taxon')"

