# This file is a part of the Sylius package.
# (c) Paweł Jędrzejewski

easy_shop_ajax:
    resource: "@EasyShopBundle/Resources/config/routing/ajax.yml"
    prefix: /ajax

easy_shop_partial:
    resource: "@EasyShopBundle/Resources/config/routing/partial.yml"
    prefix: /_partial

easy_shop_security:
    resource: "@EasyShopBundle/Resources/config/routing/security.yml"

easy_shop_user:
    resource: "@EasyShopBundle/Resources/config/routing/shop_user.yml"

easy_shop_product:
    resource: "@EasyShopBundle/Resources/config/routing/product.yml"

easy_shop_product_review:
    resource: "@EasyShopBundle/Resources/config/routing/product_review.yml"
    prefix: /products/{slug}/reviews

easy_shop_cart:
    resource: "@EasyShopBundle/Resources/config/routing/cart.yml"
    prefix: /cart

easy_shop_checkout:
    resource: "@EasyShopBundle/Resources/config/routing/checkout.yml"
    prefix: /checkout

easy_shop_order:
    resource: "@EasyShopBundle/Resources/config/routing/order.yml"
    prefix: /order

easy_shop_account:
    resource: "@EasyShopBundle/Resources/config/routing/account.yml"
    prefix: /account

easy_shop_switch_currency:
    path: /switch-currency/{code}
    methods: [GET]
    defaults:
        _controller: sylius.controller.shop.currency_switch:switchAction

easy_shop_switch_locale:
    path: /switch-locale/{code}
    methods: [GET]
    defaults:
        _controller: sylius.controller.shop.locale_switch:switchAction
