# This file is a part of the Sylius package.
# (c) Paweł Jędrzejewski

easy_shop_account_order_index:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:indexAction
        _sylius:
            section: shop_account
            template: "@EasyShop/front/Account/Order/index.html.twig"
            grid: sylius_shop_account_order

sylius_shop_account_order_show:
    path: /{number}
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:showAction
        _sylius:
            section: shop_account
            template: "@EasyShop/front/Account/Order/show.html.twig"
            repository:
                method: findOneByNumberAndCustomer
                arguments:
                    - $number
                    - "expr:service('sylius.context.customer').getCustomer()"
