# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_mailer:
    emails:
        order_confirmation:
            subject: sylius.emails.order_confirmation.subject
            template: "@EasyShop/front/Email/orderConfirmation.html.twig"
        user_registration:
            subject: sylius.emails.user_registration.subject
            template: "@EasyShop/front/Email/userRegistration.html.twig"
        password_reset:
            subject: sylius.emails.user.password_reset.subject
            template: "@EasyShop/front/Email/passwordReset.html.twig"
        reset_password_token:
            subject: sylius.emails.user.password_reset.subject
            template: "@EasyShop/front/Email/passwordReset.html.twig"
        reset_password_pin:
            subject: sylius.emails.user.password_reset.subject
            template: "@EasyShop/front/Email/passwordReset.html.twig"
        verification_token:
            subject: sylius.emails.user.verification_token.subject
            template: "@EasyShop/front/Email/verification.html.twig"
        order_confirmation_resent:
            subject: sylius.emails.order_confirmation.subject
            template: "@EasyShop/front/Email/orderConfirmation.html.twig"
        shipment_confirmation:
            subject: sylius.emails.shipment_confirmation.subject
            template: "@EasyShop/front/Email/shipmentConfirmation.html.twig"
